node_rate: 20

mpc_config:
  system_parameters:
    drone:
      mass: 0.320 # [kg]
      aerodynamic_linear_drag_coefficients:
        x: 0.08063504
        y: 0.09929089
        z: 0          # Not estimated

      attitude_control_parameters:  
        time_constants:
          roll:   0.32034106
          pitch:  0.15869484
        input_gains:
          roll:   1.02539815
          pitch:  0.95176013

    gravitational_acceleration: 9.82179 # [m/s²] - for Trondheim at sea level
    
  tuning_parameters:
    nx: 8 
    nu: 4
    m:  1

    objective_function:
      # States:    x  y  z  u     v     phi   theta psi  
      q_diagonal: [1, 1, 1, 0.25, 0.25, 0.25, 0.25, 0.01]

      # Control:   phi_ref, theta_ref, r_ref, thrust_ref
      r_diagonal: [2,       2,         0,     1]                                      
    
    prediction_horizon: 12 # Not more than 15 - otherwise too aggressive
    robust_horizon:     0
    time_step:          0.05  # [s] 

    # Should add the constraints here - future revision
    constraints:
      x:
        lb: [-inf, -inf, -100, -4, -4, -5*np.pi/180.0, -5*np.pi/180.0, -10*np.pi/180.0]
        ub: [inf, inf, 0.5, 4, 4, 5*np.pi/180.0, 5*np.pi/180.0, 10*np.pi/180.0]
      u:
        lb: [-5*np.pi/180.0, -5*np.pi/180.0, -10*np.pi/180.0, -0.15]
        ub: [5*np.pi/180.0, 5*np.pi/180.0, 10*np.pi/180.0, 0.15]

  solving_parameters:
    collocation_degree: 2
    solver_options:
      solver: "mumps"  # MA57 is recommended, https://www.hsl.rl.ac.uk/ipopt/, but some installation is broken
      debug_level: 1
