node_name: "mpc_node"
node_rate: 20

attitude_limits:
  pitch: [-5, 5]  # deg
  roll: [-5, 5]   # deg

use_optical_flow_velocities: false  # true -> Using velocity estimates from optical_flow
                                    # false -> Using polled velocity estimates 

mpc_config:
  system_parameters:
    drone:
      mass: 0.320 # [kg]
      aerodynamic_linear_drag_coefficients:
        x: 0.08063504
        y: 0.09929089
        z: 0          # Not estimated

      attitude_control_parameters:  
        time_constants:
          roll:   0.32034106
          pitch:  0.15869484
        input_gains:
          roll:   1.02539815
          pitch:  0.95176013

    gravitational_acceleration: 9.82179 # [m/s²] - for Trondheim at sea level
    
  tuning_parameters:
    nx: 9
    nu: 4
    m: 1

    objective_function:
      q_diagonal: [2, 2, 1.5, 1.25, 1.25, 1, 0.5, 0.5, 0.001]
      r_diagonal: [1, 1, 0, 1]
    
    # slack_constraints: [0, 0, 0] 

    # bounds:
    #   x:
    #     lb: [-inf, -inf, -inf, -2, -2, -0.1, -10*np.pi/180.0, -10*np.pi/180.0, -inf]
    #     ub: [inf, inf, inf, 2, 2, 0.1, 10*np.pi/180.0, 10*np.pi/180.0, inf]
    #   u:
    #     lb: [-10*np.pi/180.0, -10*np.pi/180.0, -25*np.pi/180.0, -1.0]
    #     ub: [10*np.pi/180.0, 10*np.pi/180.0, 25*np.pi/180.0, 1.0]
      
    
    prediction_horizon: 10
    robust_horizon: 0
    time_step: 0.2          # [s] 

  solving_parameters:
    collocation_degree: 2
    solver_options:
      solver: "MA57"  # MA57 is recommended, https://www.hsl.rl.ac.uk/ipopt/
                      # but struggled to get it installed
      debug_level: 0
