# Following the notation in Fossen 2021

string coordinate_frame # Alternatives: [ECEF, NED, RELATIVE_TO_PLATFORM]

# Drone desired position
float32 x       # [m]
float32 y       # [m]
float32 z       # [m]

# Drone desired heading
float32 psi     # [rad]  
---
bool success