node_name: "mission_executor_node"
node_rate: 10


maximum_expected_action_time_s:
  communicate: 5
  takeoff: 10
  land: 10
  drop_bouya: 10
  travel_to: 120
  track: 120
  search: 180
  idle: 99999


interface_name:
  takeoff: "/drone/cmd/takeoff"
  landing: "/drone/cmd/land"


enable_controller_service_names:
  velocity_controller: "/velocity_controller/service/enable_controller"


horizontal_radius_of_acceptance: 5.0  # When the drone is within 5 meters from the desired point, it has travelled to the destination
vertical_radius_of_acceptance: 7.5    # Less strict about the vertical position

max_pos_tracking_error_normed: 0.25

locations_ned:
  helipad: [0, 0, 0]


