ground_truths:
  drone_pose_helipad_frame:
    name: drone_pose_helipad_frame
    num_states: 6
    topic:
      sim: /ground_truth/helipad_frame/drone_pose
      real: /ground_truth/helipad_frame/drone_pose
    file_header: "Format: timestamp[sec] x[m], y[m], z[m], phi[deg], theta[deg], psi[deg]]\n"
    max_values_stored_in_buffer: 10

  helipad_pose_body_frame:
    name: helipad_pose_body_frame
    num_states: 6
    topic:
      sim: /ground_truth/body_frame/helipad_pose
      real: /ground_truth/body_frame/helipad_pose
    file_header: "Format: timestamp[sec] x[m], y[m], z[m], phi[deg], theta[deg], psi[deg]]\n"
    max_values_stored_in_buffer: 10

  helipad_pose:
    name: helipad_pose
    num_states: 6
    topic:
      sim: /ground_truth/ned_frame/helipad_pose
      real: /qualisys/Platform/pose
    file_header: "Format: timestamp[sec] x[m], y[m], z[m], phi[deg], theta[deg], psi[deg]]\n"
    max_values_stored_in_buffer: 10

  drone_pose_ned:
    name: drone_pose_ned
    num_states: 6
    topic:
      sim: /ground_truth/ned_frame/drone_pose
      real: /qualisys/Anafi/pose
    file_header: "Format: timestamp[sec] x[m], y[m], z[m], phi[deg], theta[deg], psi[deg]]\n"
    max_values_stored_in_buffer: 10

  drone_velocity_body_frame_and_attitude:
    name: drone_velocity_body_frame_and_attitude
    num_states: 6
    topic:
      sim: "none"
      real: /qualisys/Anafi/odom
    file_header: "Format: timestamp[sec] vx[m], vy[m], vz[m] phi[deg], theta[deg], psi[deg]\n"
    max_values_stored_in_buffer: 10

estimates:
  anafi_height:
    name: anafi_height
    num_states: 1
    topic:
      sim: /anafi/height
      real: /anafi/height
    file_header: "Format: timestamp[sec] z[m]\n"
    max_values_stored_in_buffer: 10

  anafi_attitude:
    name: anafi_attitude
    num_states: 3
    topic:
      sim: /anafi/attitude
      real: /anafi/attitude
    file_header: "Format: timestamp[sec] phi[deg], theta[deg], psi[deg]\n"
    max_values_stored_in_buffer: 5


  anafi_optical_flow:
    name: anafi_optical_flow
    num_states: 3
    topic:
      sim: /anafi/optical_flow_velocities
      real: /anafi/optical_flow_velocities
    file_header: "Format: timestamp[sec] vx[m], vy[m], vz[m]\n"
    max_values_stored_in_buffer: 5

  anafi_polled_vel:
    name: anafi_polled_vel
    num_states: 3
    topic:
      sim: /anafi/polled_body_velocities
      real: /anafi/polled_body_velocities
    file_header: "Format: timestamp[sec] vx[m], vy[m], vz[m]\n"
    max_values_stored_in_buffer: 5

  guidance_pid:
    name: guidance_pid
    num_states: 3
    topic:
      sim: /guidance/pid/velocity_reference
      real: /guidance/pid/velocity_reference
    file_header: "Format: timestamp[sec] linear, angular\n"
    max_values_stored_in_buffer: 6

  guidance_pure_pursuit:
    name: guidance_pure_pursuit
    num_states: 3
    topic:
      sim: /guidance/pure_pursuit/velocity_reference
      real: /guidance/pure_pursuit/velocity_reference
    file_header: "Format: timestamp[sec] linear, angular\n"
    max_values_stored_in_buffer: 6

  dnn_cv_position:
    name: dnn_cv_position
    num_states: 3
    topic:
      sim: /estimate/dnn_cv/position
      real: /estimate/dnn_cv/position
    file_header: "Format: timestamp[sec] [x[m], y[m], z[m]]\n"
    max_values_stored_in_buffer: 10

  dnn_cv_heading:
    name: dnn_cv_heading
    num_states: 1
    topic:
      sim: /estimate/dnn_cv/heading
      real: /estimate/dnn_cv/heading
    file_header: "Format: timestamp[sec] psi[deg]]\n"
    max_values_stored_in_buffer: 5

  tcv_pose:
    name: tcv_pose
    num_states: 6
    topic:
      sim: /estimate/tcv/pose
      real: /estimate/tcv/pose
    file_header: "Format: timestamp[sec] [x[m], y[m], z[m], phi[deg] theta[deg] psi[deg]]\n"
    max_values_stored_in_buffer: 1

  ekf_position:
    name: ekf_position
    num_states: 12 # 3 states + 3x3 covariance matrix
    topic:
      sim: /estimate/ekf
      real: /estimate/ekf
    file_header: "Format: timestamp[sec] [x[m], y[m], z[m],
                  covariance for each state (flattened 3x3 matrix)]\n"
    max_values_stored_in_buffer: 10

commands:
  attitude_cmd:
    name: attitude_cmd
    num_states: 4
    topic:
      sim: /anafi/cmd_rpyt
      real: /anafi/cmd_rpyt
    file_header: "Format: timestamp[sec] roll[deg], pitch[deg], yaw[deg], thrust[m/s]\n"
    max_values_stored_in_buffer: 1
