node_name: "pure_pursuit_guidance_node"
node_rate: 20

velocity_limits:
  vx: [-0.3, 0.3]
  vy: [-0.3, 0.3]
  vz: [-0.1, 0.1]

pure_pursuit_parameters:
  ua_max: 1.0     # Look this up later
  lookahead: 2.0  # Smaller lookahead gives more aggressive guidance
  kappa: 0.2      # Might be too small for our use case

max_error_normed: 10  # [m] Outside of this error, the pure pursuit guidance
                      # law will not be used
